# -*- coding: utf-8 -*-
"""Copy of ShAI_BootCamp_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115cEAGY1PlKEyEQkwCw3jaz6hQCnU-WN

#About Dataset
salaries dataset generally provides information about the employees of an organization in relation to their compensation. It typically includes details such as how much each employee is paid (their salary), their job titles, the departments they work in, and possibly additional information like their level of experience, education, and employment history within the organization.

# Features
- 'Id'
- 'EmployeeName'
- 'JobTitle'
- 'BasePay'
- 'OvertimePay'
- 'OtherPay'
- 'Benefits'
- 'TotalPay' -> salary
- 'TotalPayBenefits'
- 'Year'
- 'Notes'
- 'Agency'
- 'Status'

# Tasks

1. **Basic Data Exploration**: Identify the number of rows and columns in the dataset, determine the data types of each column, and check for missing values in each column.

2. **Descriptive Statistics**: Calculate basic statistics mean, median, mode, minimum, and maximum salary, determine the range of salaries, and find the standard deviation.

3. **Data Cleaning**: Handle missing data by suitable method with explain why you use it.

4. **Basic Data Visualization**: Create histograms or bar charts to visualize the distribution of salaries, and use pie charts to represent the proportion of employees in different departments.

5. **Grouped Analysis**: Group the data by one or more columns and calculate summary statistics for each group, and compare the average salaries across different groups.

6. **Simple Correlation Analysis**: Identify any correlation between salary and another numerical column, and plot a scatter plot to visualize the relationship.

8. **Summary of Insights**: Write a brief report summarizing the findings and insights from the analyses.

# Very Important Note
There is no fixed or singular solution for this assignment, so if anything is not clear, please do what you understand and provide an explanation.
"""

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/content/Salaries.csv', error_bad_lines=False)
df.head()

df.columns

#basic Data Exploration

#number of rows and columns

num_rows, num_columns = df.shape
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

print("---------------------------------------")

# Display data types of each column
data_types = df.dtypes
print("\nData types of each column:")
print(data_types)
print("---------------------------------------")

# Check for missing values in each column

missing_values = df.isnull().sum()
print("\nMissing values in each column:")
print(missing_values)

#Descriptive Statistics

mean_salary = df['TotalPay'].mean()
median_salary = df['TotalPay'].median()
mode_salary = df['TotalPay'].mode()[0]  # Mode can be a Series, take the first value
min_salary = df['TotalPay'].min()
max_salary = df['TotalPay'].max()
salary_range = max_salary - min_salary
std_dev_salary = df['TotalPay'].std()


print(f"Mean Salary: {mean_salary:.2f}")
print(f"Median Salary: {median_salary:.2f}")
print(f"Mode Salary: {mode_salary:.2f}")
print(f"Minimum Salary: {min_salary:.2f}")
print(f"Maximum Salary: {max_salary:.2f}")
print(f"Salary Range: {salary_range:.2f}")
print(f"Standard Deviation of Salary: {std_dev_salary:.2f}")

#handling missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)
#as the number of missing values is not low we cant just delete the rows n columns so we will just fill it with the mean

# Impute missing values with the mean
df['BasePay'].fillna(df['BasePay'].mean(), inplace=True)
df['TotalPay'].fillna(df['TotalPay'].mean(), inplace=True)


#i droped notes & status column as most of them were missing values
df['Agency'].fillna(value=0, inplace=True)
df['Benefits'].fillna(value=0, inplace=True)
df['TotalPayBenefits'].fillna(value=0, inplace=True)
df['OvertimePay'].fillna(value=0, inplace=True)
df['Year'].fillna(value=2011, inplace=True)
df['OtherPay'].fillna(value=0, inplace=True)

#Basic Data Visualization
import matplotlib.pyplot as plt

# Visualization of Salary Distribution (Histogram)
plt.figure(figsize=(10, 6))
plt.hist(df['TotalPay'], bins=20, color='blue', alpha=0.7)
plt.title('Salary Distribution')
plt.xlabel('TotalPay')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

grouped_data = df.groupby('OtherPay')['TotalPay'].agg(['count', 'mean', 'median', 'min', 'max'])

# Display the grouped summary statistics
print(grouped_data)


plt.figure(figsize=(10, 6))
plt.bar(grouped_data.index, grouped_data['mean'], color='skyblue')
plt.title('Average Salary Across Different Departments')
plt.xlabel('OtherPay')
plt.ylabel('TotalPay')
plt.show()

"""Employee Data Analysis Report



1. Overview:

The dataset contains information about employees, including salary and department.
2. Missing Values:

The dataset was inspected for missing values.

3. Descriptive Statistics:

Descriptive statistics were calculated for the 'salary' column, revealing insights into the salary distribution:
Mean Salary: [73682.03]
Median Salary: [70679.91]
Mode Salary: [0.00]
Minimum Salary: [618.13]
Maximum Salary: [567595.43]
Salary Range: [568213.56]
Standard Deviation of Salary: [51358.40]
4. Visualizations:

Histogram: A histogram was created to visualize the distribution of salaries.
[

"""